version: '3'

volumes:
  config_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${CONFIG_FOLDER}"

services:
  motley_cue_pam_ssh:
    build:
      context: .
      target: build
    ports:
      - "8080:8080"
      - "1022:22"
    volumes:
      - config_files:/config_files
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.fastapi.rule=Host(`localhost`)"
    #   - "traefik.http.routers.fastapi.tls=true"
  # traefik:
  #   image: traefik
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"