version: '3'

volumes:
  motley_cue_sock:

services:
  motley_cue_pam_ssh:
    build:
      context: .
      target: motley_cue_pam_ssh
    init: true
    restart: on-failure
    ports:
      - "1022:22"
    environment:
      - UID
      - GID
    volumes:
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue

  nginx:
    build:
      context: .
      target: nginx
    restart: on-failure
    hostname: "mc_endpoint"
    ports:
      - "8080:8080"
    volumes:
      - motley_cue_sock:/run/motley_cue