services:
  mapper:
    build:
      context: .
    expose:
      - 80 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`localhost`)"
      - "traefik.http.routers.fastapi.tls=true"
  traefik:
    image: traefik
    ports:
      - "8080:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf