version: '3'

volumes:
  motley_cue_sock:
networks:
  my-network:
    driver: bridge

services:
  motley_cue_pam_ssh:
    build:
      context: .
      target: motley_cue_pam_ssh
    hostname: "ssh-host"
    ports:
      - "1022:22"
    networks:
      - my-network
    environment:
      - UID
      - GID
      - SHELL
    volumes:
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue

  nginx:
    build:
      context: .
      target: nginx
    hostname: "mc_endpoint"
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - ${CONFIG_FOLDER}:/config_files
      - motley_cue_sock:/run/motley_cue
